### PR TITLE
Create index-es.adoc

### PR DESCRIPTION
**Pull request by kobernyk**
Spanish translation for index.adoc

| Type | New Feature |
| :--- | :--- |
| Screenshot | no |
| Description of changes | I translated the index.adoc file to spanish |

### CODE REVIEW

**Comment by eddiejaoude** [comment]
Thanks @kobernyk 👍 

I will have a play for the best way to get this generated also, so additional pages can be translated. Thanks 🤓

**Comment by kobernyk** [comment]
You're welcome! How can I translate more pages? Would you merge the pull requests?

**Comment by eddiejaoude** [comment]
Yes, I want to accept the pull request, but first I need to think about where to put the link to change between the languages 🤓 .

We will merge it soon 👍 

If you are keen to translate more pages, I would suggest go through the `do` [files](https://github.com/eddiejaoude/book-open-source-tips/tree/master/src/do) and create a new file with the language appended, for example `do-accessible.adoc` to be `do-accessible-es.adoc`

**Comment by kobernyk** [comment]
Great! I'll be translating more pages then :)

**Pull request merged**
