### PR TITLE
Create do-explore-open-source-projects-es.adoc

### PR DESCRIPTION
**Pull request by kobernyk**
Spanish translation for do-explore-open-source-projects.adoc

### CODE REVIEW

**Comment by eddiejaoude** [comment]
Thanks 👍

**Comment by kobernyk** [comment]
Hey @eddiejaoude! I won't be able to translate anything this week since I'll be very busy studying for my exams. I'll be back collaborating in a week or so :)

**Comment by eddiejaoude** [comment]
Hey @kobernyk , no problem, good luck in your exams 📖 🤓 👍

**Comment by kobernyk** [comment]
Thank you :D

**Pull request merged**
