### PR TITLE
Create do-automation-es.adoc

### PR DESCRIPTION
**Pull request by kobernyk**
Spanish translation for do-automation.adoc

### CODE REVIEW

**Comment by eddiejaoude** [comment]
Great 👍. 

Can you also update the DO-es link page that allows people to navigate to the page https://github.com/eddiejaoude/book-open-source-tips/blob/master/src/do-es.adoc

**Comment by kobernyk** [comment]
Uhm, I don't understand, do you want me to translate the name of the files or the files themselves?

**Comment by eddiejaoude** [comment]
To include the page you translated `do-automation-es.adoc`, we need to update the _include_ on the `do-es.adoc` file. Currently all these includes point to the English version, and we can update them as they get translated by appending `-es` to the file name.

In the file `do-automation-es.adoc` If you could update the _include_ for the translated automation file by changing `include::do/do-automation.adoc[]` to `include::do/do-automation-es.adoc[]` then I can merge your PR. I hope that makes sense, if not let me know 🤓

**Comment by eddiejaoude** [comment]
I will merge this and I can sort out the link 🤓

**Comment by kobernyk** [comment]
Did I do what you wanted me to do?

**Comment by eddiejaoude** [comment]
No problem, you did the difficult part and just did the easy part. I updated the `do-es.adoc` links as you translate new files https://github.com/eddiejaoude/book-open-source-tips/blob/master/src/do-es.adoc

**Comment by kobernyk** [comment]
I'm sorry 🙈

**Pull request merged**
