### PR TITLE
Cleaned root directory by moving GitHub template files to hidden .github directory

### LINKED ISSUE #7: Move GitHub templates to hidden directory
Please remove items in the right column: 

| Type | Idea |
| :--- | :--- |
| Screenshot included? | no |
| Description | Clean up root directory by moving GitHub template files to hidden `.github` directory |

### PR DESCRIPTION
**Pull request by kalpeshhpatel**
Closes #7 

* [x] Created .`github` folder
* [x] Moved following files to that folder
   * CODE_OF_CONDUCT.md
   * CONTRIBUTING.md
   * ISSUE_TEMPLATE.md
   * PULL_REQUEST_TEMPLATE.md
* [x] Updated the references of that file

### CODE REVIEW

**Comment by eddiejaoude** [comment]
Thanks 👍 . 

I will take a look tomorrow morning.

**Comment by kalpeshhpatel** [comment]
@eddiejaoude , sure, thanks :)

**Comment by eddiejaoude** [comment]
I reformatted the description

**Comment by eddiejaoude** [comment]
Thanks @kalpeshhpatel 👍

**Pull request merged**
