### PR TITLE
Create index-fil.adoc

### PR DESCRIPTION
**Pull request by themarshann**
Translated the index.adoc file into Filipino

### CODE REVIEW

**Comment by eddiejaoude** [comment]
@themarshann thanks for the PR. 

It looks like you deleted the `src/index.adoc` file, are you able to put it back, as we will need both files, the `src/index.adoc` and the `src/index-fil.adoc` one 🤓

**Comment by themarshann** [comment]
I think I managed to put it back. I'm not sure if I did the right thing though.

**Comment by eddiejaoude** [comment]
Sorry for my slow reply. You put back the `src/index.adoc` file, but unfortunately, it has the translations in it.

## Recommended actions

- [ ] Create `src/index-fil.adoc` with your translations
- [ ] Put back / undo `src/index.adoc` unchanged

If you have any questions let me know, Thanks again for your efforts 🤓

**Comment by themarshann** [comment]
Now I'm confused and felt like I've messed things up. Would it be better if I'll just create another PR?

**Comment by eddiejaoude** [comment]
No problem, its all good practice and good learning 🤓 .

If it is easier for you, you could close this PR and create a new one, but make sure you don't lose your translation work.

If you still have issues, we can always jump on a Slack or Gitter channel or even Google Hangouts to discuss.

**Comment by eddiejaoude** [comment]
Another option, If you want to try and solve it in this PR, you could try these steps: 

1. Undo your latest commit with a new commit that does the opposite, this will not rewriting history `git revert dfda98a`
2. Undo your commit before that with a new commit that does the opposite again `git revert 8a61c77` 
3. Apply this patch of your work, this is done in the 4 steps:
   - Copying the *diff* below of your work and put it in a file called `my.patch` in the root of the project (do not commit this file)
   - Apply the patch with the command `git apply my.patch`
   - Delete the `my.patch` file so it doesn't get accidentally committed 
   - Then make your commit and push like before for your new file `src/index-fil.adoc`

```diff
diff --git a/src/index-fil.adoc b/src/index-fil.adoc
new file mode 100644
index 0000000..b7f2781
--- /dev/null
+++ b/src/index-fil.adoc
@@ -0,0 +1,54 @@
+= Mga Babalaan sa Open Source
+Ni Eddie Jaoude
+:toc:
+
+:may-akda:    Eddie Jaoude
+:twitter:   https://twitter.com/eddiejaoude
+:petsa:      2016
+:bersyon:   0.1.0
+:repo:      https://github.com/eddiejaoude/book-open-source-tips
+:imagesdir: images
+:docinfo1:
+
+[abstract]
+== Buod
+
+Ang aklat na ito ay naglalaman ng mga karaniwang DAPAT at HINDI DAPAT GAWIN para sa Open Source na software.
+
+[preface]
+== Paunang Salita
+
+Ang komunidad ng Open Source ay patuloy na lumalago. Sa bawat araw na dumarami ang bilang ng mga proyektong Open Source, gayundin ang hukbo ng mga nag-aambag para panatilihin sila. Bagaman nakakapanabik ito para sa industriya, maaari itong maging katakot-takot para sa isang bagong tagabuo sa komunidad. Ang aklat na ito ay naglalayon na magbigay ng iilang mga babalaan para sa mga baguhan upang makatulong sa kanila na iwasan ang mga patibong sa pagbuo ng Open Source at para matuto mula sa pangkalahatang kaalaman ng komunidad.
+
+Ika nga sa lumang kawikaan, "_Ang oras at ang alon [at teknolohiya] ay hindi naghihintay sa sinumang tao_". At sa abot ng aming makakaya, maging ang aklat ding ito. Tandaang tingnan ang bilang ng bersyon para sa mga update! Kami'y kasalukuyang nasa v{version}.
+
+Lubos naming ikagagalak ang inyong tulong upang mapanatiling naka-update ang aklat na ito. Ang inyong mga komento, suhestyon at pull requests ay malugod naming tinatanggap. Maaari niyong hanapin ang repository sa Github: {repo}.
+
+Kung may iba pa kayong katanungan, mangyari lamang na makipag-ugnay sa may-akda na si {author} sa {twitter}.
+
+<<<
+== Panimula
+
+Nangingibabaw ang Open Source sa industriya ng software. Ang mga kampeon nito'y pinabibilangan ng mga tanyag na organisasyon tulad ng Facebook, Twitter, Netflix, LinkedIn at Google (Android/Chrome), ngunit ang mas mahalaga, ang hukbo ng mga dedikadong indibidwal na tagabuo sa buong mundo. Ang kanilang mga pagsisikap ay nagkaroon ng epekto sa halos bawat bahagi ng computer science, nagresulta sa milyun-milyong open source na proyekto na may bilyun-bilyong mga linya ng code!
+
+Habang ang masaganang ecosystem na ito ay nagbigay ng malaking tulong sa buong industriya, maaari rin itong magpahirap sa mga baguhan na hindi alam kung saan magsisimula. Kung ikaw ay isang baguhan, maaari mong harapin ang mga katanungang _"Paano ako makakaambag sa komunidad ng Open Source?"_ O, _"Paano ako pipili sa pagitan ng napakaraming nakikipagkompetensiyang proyekto?"_. Ang mga sumusunod na mga DAPAT at HINDI DAPAT GAWIN ay naglalayon na masagot ang mga katanungang iyon, pati na rin ang ibang mga payo para sa nagbabalak na maging tagabuo ng Open Source.
+
+Tara na't sisirin natin ito.
+
+PAALALA: Ang mga proyektong hindi isinapubliko sa simula ay may mas mataas na pagkakataong ipagkatiwala ang mga pribadong kredensyal sa kasaysayan, kung kaya't mas nirerekomendang gawing pampubliko ang mga proyekto sa simula pa lang. Ang pagsasaad na sila ay hindi pa tapos ay hindi isang dahilan, dahil kailanman, sila ay hindi matatapos. Kung isinapubliko sa simula pa lamang, pinaparating lang noon na ang tamang pananaw ang ginamit kaya naman mababawasan ang panganib.
+
+
+<<<
+== Mga DAPAT Gawin
+
+include::do.adoc[]
+
+<<<
+== Mga HINDI DAPAT Gawin
+
+include::dont.adoc[]
+
+<<<
+== Apendiks
+
+include::appendix.adoc[]
```

**I hope this helps and I didn't make it more complicated, any questions let me know** 🤓

**Comment by themarshann** [comment]
I'll take a look at how to do that later. Thank you for the detailed explanation sir :)

**Comment by themarshann** [comment]
Hi, I'm sorry I didn't get back to this right away. I got busy these past few days. I think I'll just close this PR and make another one.
Hope that will be okay. Thanks! :)

**Comment by eddiejaoude** [comment]
No problem. Sure, thank you 🤓

**Pull request closed without merging**
