### PR TITLE
Updated info about Readme.md

### PR DESCRIPTION
**Pull request by Parag456**
| Bug Fix / New Feature |
| :--- | :--- |
| Screenshot | no |
| Description of changes |Below|

Added:  Include a clear description of the project and perhaps some information regarding contacting, or how you prefer people the contribute.

### CODE REVIEW

**Comment by eddiejaoude** [comment]
Good idea 👍

**Comment by jossue33** [comment]
@eddiejaoude  Hello, I would like to translate to Spanish but I do not know how. I would like to do it by means of pull request :)

**Comment by eddiejaoude** [comment]
@jossue33 that would be great! There was another suggestion for this a few weeks ago  https://github.com/eddiejaoude/book-open-source-tips/issues/55 . 

What help do you need? 

Probably a good place to start is if you could translate the one page first (roughly, you can improve it later on) and I can get it added to the build and deployment.

## Steps

- [ ] Translate this page first https://github.com/eddiejaoude/book-open-source-tips/blob/master/src/index.adoc 
- [ ] Create a PR with a new file next to the English existing one in `src/index-es.adoc` (I think `es` is the correct language code for Spanish)

Then I can add it to the workflow and we can take it from there.

Let me know if you need more information 🤓

**Comment by shadowz10** [comment]
@eddiejaoude thank you very much sorry for the delay I'll start when before

**Comment by jossue33** [comment]
@eddiejaoude  thank you very much sorry for the delay I'll start when before

**Comment by eddiejaoude** [comment]
@jossue33 no problem. Someone has started translating to Spanish already, you can see what they have done so far with the files ending in `-es.adoc` https://github.com/eddiejaoude/book-open-source-tips/tree/master/src/do

**Pull request closed without merging**
