### PR TITLE
do-readme spanish translation

### PR DESCRIPTION
**Pull request by JorgePiaggio**
| Type | Content translation |
| :--- | :--- |
| Screenshot | no |
| Description of changes | do files translation to spanish |

### CODE REVIEW

**Comment by JorgePiaggio** [comment]
I'd like to go on translating if you think these are ok.

**Comment by eddiejaoude** [comment]
Thank you @JorgePiaggio 👍 

These look great! I can not check the Spanish, but I am sure they are fine. Yes please continue 🤓

**Comment by JorgePiaggio** [comment]
Hi Eddie, I guess this PR is ready.. all do files are already translated, and I've linked the individual files in the do-es main file.
This are my first contributions, please let me know if anything is wrong.

**Comment by eddiejaoude** [comment]
Thank you @JorgePiaggio 👍 - at first glance this looks great! I need to download it and check it builds ok with Asciidoctor and probably also update CI to build this too.

I will test it shortly, thank you again for this awesome contribution 🤓

**Comment by eddiejaoude** [comment]
@JorgePiaggio this is looking great! Sorry again for being slow in reviewing.

I have a question, in the `DON’Ts` section, the sub sections are not translated there. Was this missed or it will come later in another PR? For example `Big bang project`

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍 - left 1 question about was the last section missed out by mistake or intentional

**Comment by JorgePiaggio** [comment]
> I have a question, in the DON’Ts section, the sub sections are not translated there. Was this missed or it will come later in another PR? For example Big bang project

Hi @eddiejaoude, thanks for reviewing... about the question, i didn't do the DONTs section on purpose, coz the project looked inactive for a while, so just wanted to check.... but of course i would like to do it... I have to finish reading your book!!!!

So I guess by the end of LHD: Build I'll start with that :+1:

**Comment by eddiejaoude** [comment]
No problem 👍 , thank you for your awesome work! When you get time is fine 🤓 . Yes focus on LHD: Build for now 👍 

thanks again 💪

**Comment by JorgePiaggio** [comment]
Hi Eddie, I'm ready with the DONTs section.

While translating I wondered if this PR is what you call a big bang or god PR. 

I feel like there are lots of files in here, but they kept adding themselves to the PR when i pushed them... didn't know that before.. so now i got the DONT files, should i push them so they add to this PR, or should i make a separate one?

**Comment by eddiejaoude** [comment]
Hi @JorgePiaggio , sorry for my slow reply.

Usually I would say keep PRs small, with translations I am unsure. Maybe if you have the changes push it to this PR

**Review by eddiejaoude — APPROVED** [review]
Thanks 👍

**Pull request merged**
