### PR TITLE
Create do-always-respond-es.adoc

### PR DESCRIPTION
**Pull request by kobernyk**
Spanish translation for do-always-respond.adoc

### CODE REVIEW

**Comment by eddiejaoude** [comment]
Great, thank you 👍

**Comment by eddiejaoude** [comment]
Its looking good...

screenshot 2018-02-19 07 35 53

**Comment by kobernyk** [comment]
Cool :smile:

**Comment by kobernyk** [comment]
Hey! I'm sorry I haven't been able to translate more pages, I've been busy studying. I'll be contributing again soon :)

**Comment by eddiejaoude** [comment]
No problem. When you get time. Good luck with your studies 🤓

**Comment by kobernyk** [comment]
Thank you :smile:

**Pull request merged**
